#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class AblationRow:
    setting: str
    pairs: int
    reliable_pairs: int
    hit3_all: float
    hit5_all: float
    hit10_all: float
    hit3_reliable: float
    hit5_reliable: float
    hit10_reliable: float


def _read_bool(s: str) -> bool:
    return str(s).strip().lower() in {"1", "true", "yes", "y"}


def _rate(numer: int, denom: int) -> float:
    return float(numer) / float(denom) if denom > 0 else 0.0


def _summarize_summary_csv(path: Path) -> AblationRow | None:
    if not path.is_file():
        return None
    setting = path.parent.name

    pairs = 0
    reliable_pairs = 0
    hit3 = 0
    hit5 = 0
    hit10 = 0
    hit3_rel = 0
    hit5_rel = 0
    hit10_rel = 0

    with path.open("r", encoding="utf-8", newline="") as f:
        r = csv.DictReader(f)
        for row in r:
            pairs += 1
            rel = _read_bool(row.get("reliable", "false"))
            t3 = _read_bool(row.get("top3_hit", "false"))
            t5 = _read_bool(row.get("top5_hit", "false"))
            t10 = _read_bool(row.get("top10_hit", "false"))

            if t3:
                hit3 += 1
            if t5:
                hit5 += 1
            if t10:
                hit10 += 1

            if rel:
                reliable_pairs += 1
                if t3:
                    hit3_rel += 1
                if t5:
                    hit5_rel += 1
                if t10:
                    hit10_rel += 1

    return AblationRow(
        setting=setting,
        pairs=pairs,
        reliable_pairs=reliable_pairs,
        hit3_all=_rate(hit3, pairs),
        hit5_all=_rate(hit5, pairs),
        hit10_all=_rate(hit10, pairs),
        hit3_reliable=_rate(hit3_rel, reliable_pairs),
        hit5_reliable=_rate(hit5_rel, reliable_pairs),
        hit10_reliable=_rate(hit10_rel, reliable_pairs),
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Aggregate per-setting summaries under an ablation root into one table.")
    parser.add_argument("--ablation-root", default="outputs/ablation", help="Root directory containing setting subfolders.")
    parser.add_argument("--write-md", action="store_true", help="Also write ablation_summary.md next to the CSV.")
    args = parser.parse_args()

    ablation_root = Path(args.ablation_root).resolve() if not Path(args.ablation_root).is_absolute() else Path(args.ablation_root)
    if not ablation_root.is_dir():
        print(f"Missing ablation root directory: {ablation_root}", file=sys.stderr)
        return 2

    rows: list[AblationRow] = []
    for summary_csv in sorted(ablation_root.glob("*/summary.csv")):
        r = _summarize_summary_csv(summary_csv)
        if r is not None:
            rows.append(r)

    if not rows:
        print(f"No summary.csv files found under: {ablation_root}", file=sys.stderr)
        return 3

    out_csv = ablation_root / "ablation_summary.csv"
    with out_csv.open("w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(list(AblationRow.__annotations__.keys()))
        for r in rows:
            w.writerow(
                [
                    r.setting,
                    r.pairs,
                    r.reliable_pairs,
                    f"{r.hit3_all:.6f}",
                    f"{r.hit5_all:.6f}",
                    f"{r.hit10_all:.6f}",
                    f"{r.hit3_reliable:.6f}",
                    f"{r.hit5_reliable:.6f}",
                    f"{r.hit10_reliable:.6f}",
                ]
            )
    print("Wrote:", out_csv)

    if args.write_md:
        lines: list[str] = []
        lines.append("# Ablation summary")
        lines.append("")
        lines.append(f"- Ablation root: `{ablation_root}`")
        lines.append("")
        lines.append("| Setting | Pairs | Reliable | hit@3 | hit@5 | hit@10 |")
        lines.append("| --- | ---: | ---: | ---: | ---: | ---: |")
        for r in rows:
            lines.append(f"| `{r.setting}` | {r.pairs} | {r.reliable_pairs} | {r.hit3_all:.3f} | {r.hit5_all:.3f} | {r.hit10_all:.3f} |")
        lines.append("")
        lines.append("## Notes")
        lines.append("")
        lines.append("- The hit rates are computed from each setting's `summary.csv` (generated by `scripts/make_summary.py`).")
        lines.append("- Use the reliable-only columns in the CSV if you enable a stricter QC gate.")

        out_md = ablation_root / "ablation_summary.md"
        out_md.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print("Wrote:", out_md)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
